import { Track } from '@/components/sharedTypes/track';

export const data: Track[] = [
  {
    _id: 8,
    name: 'Chase',
    author: 'Alexander Nakarada',
    release_date: '2005-06-11',
    genre: ['Классическая музыка'],
    duration_in_seconds: 205,
    album: 'Chase',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    _id: 9,
    name: 'Salamander Ego',
    author: 'Kevin MacLeod',
    release_date: '2020-02-11',
    genre: ['Кантри'],
    duration_in_seconds: 105,
    album: 'Salamander Ego',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_Salamander_Ego.mp3',
    stared_user: [],
  },
  {
    _id: 10,
    name: 'Welcome to the Party',
    author: 'Cooper Cannell',
    release_date: '2020-02-11',
    genre: ['Рок'],
    duration_in_seconds: 95,
    album: 'Welcome to the Party',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Cooper_Cannell_-_Welcome_to_the_Party.mp3',
    stared_user: [],
  },
  {
    _id: 11,
    name: 'Fluffing a Duck',
    author: 'Kevin MacLeod',
    release_date: '2020-02-11',
    genre: ['Электронная музыка'],
    duration_in_seconds: 208,
    album: 'Fluffing a Duck',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_Fluffing_a_Duck.mp3',
    stared_user: [],
  },
  {
    _id: 12,
    name: 'Rockstar',
    author: 'Audionautix',
    release_date: '2020-02-11',
    genre: ['Рок'],
    duration_in_seconds: 165,
    album: 'Rockstar',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Audionautix_-_Rockstar.mp3',
    stared_user: [],
  },
  {
    _id: 13,
    name: 'Enthusiast',
    author: 'Tours',
    release_date: '2020-02-11',
    genre: ['Электронная музыка'],
    duration_in_seconds: 123,
    album: 'Enthusiast',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Tours_-_Enthusiast.mp3',
    stared_user: [],
  },
  {
    _id: 14,
    name: 'UFO',
    author: 'Kevin MacLeod',
    release_date: '2020-02-11',
    genre: ['Электронная музыка'],
    duration_in_seconds: 164,
    album: 'UFO',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_UFO.mp3',
    stared_user: [],
  },
  {
    _id: 15,
    name: 'Islamander Light',
    author: 'Moombahton',
    release_date: '2020-02-11',
    genre: ['Электронная музыка'],
    duration_in_seconds: 156,
    album: 'Islamander Light',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Moombahton_-_Islamander_Light.mp3',
    stared_user: [],
  },
  {
    _id: 16,
    name: 'Midnight Tale',
    author: 'Freedom Trail Studio',
    release_date: '2020-02-11',
    genre: ['Классическая музыка'],
    duration_in_seconds: 187,
    album: 'Midnight Tale',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Freedom_Trail_Studio_-_Midnight_Tale.mp3',
    stared_user: [],
  },
  {
    _id: 17,
    name: 'Chale',
    author: 'Alexander Nesterenko',
    release_date: '2020-02-11',
    genre: ['Рок'],
    duration_in_seconds: 145,
    album: 'Chale',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Alexander_Nesterenko_-_Chale.mp3',
    stared_user: [],
  },
  {
    _id: 18,
    name: 'The Longest Year',
    author: 'Kevin MacLeod',
    release_date: '2020-02-11',
    genre: ['Кантри'],
    duration_in_seconds: 178,
    album: 'The Longest Year',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_The_Longest_Year.mp3',
    stared_user: [],
  },
  {
    _id: 19,
    name: 'Summer',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 134,
    album: 'Summer',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Summer.mp3',
    stared_user: [],
  },
  {
    _id: 20,
    name: 'Sunshine',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 167,
    album: 'Sunshine',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Sunshine.mp3',
    stared_user: [],
  },
  {
    _id: 21,
    name: 'Winter',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 189,
    album: 'Winter',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Winter.mp3',
    stared_user: [],
  },
  {
    _id: 22,
    name: 'Spring',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 156,
    album: 'Spring',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Spring.mp3',
    stared_user: [],
  },
  {
    _id: 23,
    name: 'Autumn',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 172,
    album: 'Autumn',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Autumn.mp3',
    stared_user: [],
  },
  {
    _id: 24,
    name: 'Rain',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 148,
    album: 'Rain',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Rain.mp3',
    stared_user: [],
  },
  {
    _id: 25,
    name: 'Snow',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 163,
    album: 'Snow',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Snow.mp3',
    stared_user: [],
  },
  {
    _id: 26,
    name: 'Wind',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 151,
    album: 'Wind',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Wind.mp3',
    stared_user: [],
  },
  {
    _id: 27,
    name: 'Fire',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 175,
    album: 'Fire',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Fire.mp3',
    stared_user: [],
  },
  {
    _id: 28,
    name: 'Earth',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 142,
    album: 'Earth',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Earth.mp3',
    stared_user: [],
  },
];
