import { Track } from '@/components/sharedTypes/track';

export const data: Track[] = [
  {
    _id: 8,
    name: 'Chase',
    author: 'Alexander Nakarada',
    release_date: '2005-06-11',
    genre: ['Классическая музыка'],
    duration_in_seconds: 205,
    album: 'Chase',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    _id: 9,
    name: 'Salamander Ego',
    author: 'Kevin MacLeod',
    release_date: '2020-02-11',
    genre: ['Кантри'],
    duration_in_seconds: 105,
    album: 'Salamander Ego',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_Salamander_Ego.mp3',
    stared_user: [],
  },
  {
    _id: 10,
    name: 'Welcome to the Party',
    author: 'Cooper Cannell',
    release_date: '2019-03-12',
    genre: ['Кантри'],
    duration_in_seconds: 234,
    album: 'Welcome to the Party',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Cooper_Cannell_-_Welcome_to_the_Party.mp3',
    stared_user: [],
  },
  {
    _id: 11,
    name: 'Fluffing a Duck',
    author: 'Kevin MacLeod',
    release_date: '2011-06-12',
    genre: ['Электроника'],
    duration_in_seconds: 103,
    album: 'Fluffing a Duck',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_Fluffing_a_Duck.mp3',
    stared_user: [],
  },
  {
    _id: 12,
    name: 'Rockstar',
    author: 'Audionautix',
    release_date: '2015-06-12',
    genre: ['Рок'],
    duration_in_seconds: 197,
    album: 'Rockstar',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Audionautix_-_Rockstar.mp3',
    stared_user: [],
  },
  {
    _id: 13,
    name: 'Enthusiast',
    author: 'Tours',
    release_date: '2015-06-12',
    genre: ['Электроника'],
    duration_in_seconds: 185,
    album: 'Enthusiast',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Tours_-_Enthusiast.mp3',
    stared_user: [],
  },
  {
    _id: 14,
    name: 'Shipping Lanes',
    author: 'Chad Crouch',
    release_date: '2015-06-12',
    genre: ['Кантри'],
    duration_in_seconds: 126,
    album: 'Shipping Lanes',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Chad_Crouch_-_Shipping_Lanes.mp3',
    stared_user: [],
  },
  {
    _id: 15,
    name: 'PFM',
    author: 'Ilya Truhanov',
    release_date: '2017-05-18',
    genre: ['Инди'],
    duration_in_seconds: 163,
    album: 'PFM',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Ilya_Truhanov_-_PFM.mp3',
    stared_user: [],
  },
  {
    _id: 16,
    name: 'Midnight Tale',
    author: 'Freedom Trail Studio',
    release_date: '2018-03-24',
    genre: ['Кантри'],
    duration_in_seconds: 227,
    album: 'Midnight Tale',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Freedom_Trail_Studio_-_Midnight_Tale.mp3',
    stared_user: [],
  },
  {
    _id: 17,
    name: 'Signature',
    author: 'Jeremy Blake',
    release_date: '2017-06-09',
    genre: ['Электроника'],
    duration_in_seconds: 179,
    album: 'Signature',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Jeremy_Blake_-_Signature.mp3',
    stared_user: [],
  },
  {
    _id: 18,
    name: 'Brave',
    author: 'Aakash Gandhi',
    release_date: '2019-03-18',
    genre: ['Рок'],
    duration_in_seconds: 192,
    album: 'Brave',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Aakash_Gandhi_-_Brave.mp3',
    stared_user: [],
  },
  {
    _id: 19,
    name: 'Dreams',
    author: 'Aakash Gandhi',
    release_date: '2019-03-18',
    genre: ['Рок'],
    duration_in_seconds: 234,
    album: 'Dreams',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Aakash_Gandhi_-_Dreams.mp3',
    stared_user: [],
  },
  {
    _id: 20,
    name: 'Me & You',
    author: 'Gravity Sound',
    release_date: '2020-02-14',
    genre: ['Поп'],
    duration_in_seconds: 173,
    album: 'Me & You',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Gravity_Sound_-_Me_and_You.mp3',
    stared_user: [],
  },
  {
    _id: 21,
    name: 'Soul',
    author: 'Gravity Sound',
    release_date: '2020-04-27',
    genre: ['Поп'],
    duration_in_seconds: 196,
    album: 'Soul',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Gravity_Sound_-_Soul.mp3',
    stared_user: [],
  },
  {
    _id: 22,
    name: 'World',
    author: 'Gravity Sound',
    release_date: '2020-07-06',
    genre: ['Поп'],
    duration_in_seconds: 206,
    album: 'World',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Gravity_Sound_-_World.mp3',
    stared_user: [],
  },
  {
    _id: 23,
    name: 'Time',
    author: 'Gravity Sound',
    release_date: '2020-11-15',
    genre: ['Поп'],
    duration_in_seconds: 206,
    album: 'Time',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Gravity_Sound_-_Time.mp3',
    stared_user: [],
  },
  {
    _id: 24,
    name: 'Puppy',
    author: 'Gravity Sound',
    release_date: '2021-02-05',
    genre: ['Поп'],
    duration_in_seconds: 173,
    album: 'Puppy',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Gravity_Sound_-_Puppy.mp3',
    stared_user: [],
  },
  {
    _id: 25,
    name: 'Puppy2',
    author: 'Gravity Sound',
    release_date: '2021-03-17',
    genre: ['Поп'],
    duration_in_seconds: 251,
    album: 'Puppy',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Gravity_Sound_-_Puppy.mp3',
    stared_user: [],
  },
  {
    _id: 26,
    name: 'Puppy3',
    author: 'Gravity Sound',
    release_date: '2021-05-14',
    genre: ['Поп'],
    duration_in_seconds: 229,
    album: 'Puppy',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Gravity_Sound_-_Puppy.mp3',
    stared_user: [],
  },
  {
    _id: 27,
    name: 'Puppy4',
    author: 'Gravity Sound',
    release_date: '2021-07-16',
    genre: ['Поп'],
    duration_in_seconds: 250,
    album: 'Puppy',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Gravity_Sound_-_Puppy.mp3',
    stared_user: [],
  },
  {
    _id: 28,
    name: 'Puppy5',
    author: 'Gravity Sound',
    release_date: '2021-08-24',
    genre: ['Поп'],
    duration_in_seconds: 239,
    album: 'Puppy',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Gravity_Sound_-_Puppy.mp3',
    stared_user: [],
  },
];
